from collections import Counter
from typing import List

import pytest

@pytest.mark.data('''.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............''', 21, 40)
def test_07(data: List[str], level):
    curr_pos = {data[0].index("S"): 1}
    gcnt = 0

    for line in data:
        next_pos = Counter()
        for pos, cnt in curr_pos.items():
            if line[pos] == "^":
                next_pos[pos-1] += cnt
                next_pos[pos+1] += cnt
                gcnt += 1
            else:
                next_pos[pos] += cnt
        curr_pos = next_pos
    return sum(curr_pos.values()) if level else gcnt